# Generated by Django 4.0.2 on 2023-02-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active_hatms',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hatms_created',
        ),
    ]
