# Generated by Django 4.0.2 on 2023-01-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hatims_created',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
