# Generated by Django 4.0.2 on 2023-01-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_customuser_hatims_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_hatims',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
