# Generated by Django 4.0.2 on 2023-01-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_customuser_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='active_hatims',
            new_name='active_hatms',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='hatims_created',
            new_name='hatms_created',
        ),
    ]
