# Generated by Django 4.0.2 on 2023-01-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_rename_active_hatims_customuser_active_hatms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
