# Generated by Django 4.0.2 on 2023-01-20 18:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hatim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPublic', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
            ],
            options={
                'verbose_name': 'Hatim',
                'verbose_name_plural': 'Hatims',
            },
        ),
        migrations.CreateModel(
            name='Juz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juz_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('status', models.CharField(choices=[('free', 'Free'), ('in Progress', 'In Progress'), ('completed', 'Completed')], default='free', max_length=20)),
                ('hatim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juz', to='hatim.hatim')),
            ],
            options={
                'verbose_name': 'Juz',
                'verbose_name_plural': 'Juzs',
            },
        ),
    ]
