# Generated by Django 4.0.2 on 2023-02-10 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hatm', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juz',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juz_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
