# Generated by Django 4.0.2 on 2023-01-30 14:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hatm', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hatim',
            new_name='Hatm',
        ),
        migrations.AlterModelOptions(
            name='hatm',
            options={'verbose_name': 'Hatm', 'verbose_name_plural': 'Hatms'},
        ),
    ]
