# Generated by Django 4.0.2 on 2023-01-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hatim', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hatim',
            old_name='creator_id',
            new_name='user_idj',
        ),
    ]
