# Generated by Django 4.0.2 on 2023-06-02 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hatm', '0003_hatm_members_joinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatm',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
