# Generated by Django 4.0.2 on 2023-01-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hatm', '0003_rename_hatim_hatm_alter_hatm_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juz',
            old_name='hatim_id',
            new_name='hatm_id',
        ),
    ]
