# Generated by Django 4.0.2 on 2023-01-21 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatim', '0005_hatim_iscompleted_juz_type_alter_juz_juz_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatim',
            name='created_at',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
    ]
