# Generated by Django 4.0.2 on 2023-01-21 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatim', '0004_rename_user_idj_hatim_creator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatim',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='juz',
            name='type',
            field=models.CharField(choices=[('juz', 'Juz'), ('dua', 'Dua')], default='juz', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='juz',
            name='juz_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
